### ISSUE TITLE
Make it simpler to just print a value.

### ISSUE THREAD

**Issue by wdanilo** [ct-austin/ifmt#3]
Hi! First of all, thanks for this lib. It is so nicer to write rust code using it!
Secondly, I think there is a small room for improvement. For example, why don't we allow the following code to compile?

```rust
iprintln!(canvas.code());
```

It should be converted either to `iprintln!("{}", canvas.code());` or to `iprintln!("{:?}", canvas.code());`. I prefer the latter, but I'm ok with both. In any case, that would allow us for much simpler usage in many cases.

Thanks! :)

**Comment by ct-austin** [comment]
I have done some work on an adjusted syntax which would subsume this request, where syntax highlighting can be kept for all interpolated values.

Instead of
```rust
iprintln!("{canvas.code():?}");
iprintln!("x: {x}, y: {y}, x + y: {x + y}");
```
you could instead write something along the lines of
```rust
iprintln!(canvas.code();?);
iprintln!("x: " x "y: " y ", x + y: " x + y);
```

Since it seems there's some interest I'll have to get working on it again.

**Comment by ct-austin** [comment]
Support for the adjusted syntax has been added with version 0.3.
